// Simulates the outgoing-call traffic (Stripe, Twilio, Google Maps) that a real
// e-commerce backend would generate, plus a few deliberate anomalies so you can
// see the security-flag engine fire. Incoming /api/orders traffic is real —
// generated by hitting demo-app/server.js directly; this script fills in the rest.
//
// Usage: node simulate-traffic.js <projectKey> [backendUrl]

const http = require('http');
const https = require('https');
const { URL } = require('url');

const projectKey = process.argv[2];
const backendUrl = process.argv[3] || 'http://localhost:4000';

if (!projectKey) {
  console.error('Usage: node simulate-traffic.js <projectKey> [backendUrl]');
  process.exit(1);
}

function postJSON(urlStr, payload) {
  return new Promise((resolve, reject) => {
    const target = new URL(urlStr);
    const isHttps = target.protocol === 'https:';
    const body = JSON.stringify(payload);
    const req = (isHttps ? https : http).request({
      hostname: target.hostname,
      port: target.port || (isHttps ? 443 : 80),
      path: target.pathname,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    }, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => resolve({ status: res.statusCode, data }));
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }

// baseline "healthy" outgoing calls, mirroring the sample table in the project spec
function healthyBatch() {
  const events = [];
  events.push({ projectKey, type: 'outgoing', api: 'https://api.stripe.com/charges', method: 'POST', duration: rand(300, 500), status: 200 });
  events.push({ projectKey, type: 'outgoing', api: 'https://api.twilio.com/messages', method: 'POST', duration: rand(100, 220), status: 200 });
  events.push({ projectKey, type: 'outgoing', api: 'https://maps.googleapis.com/geocode', method: 'GET', duration: rand(200, 400), status: 200 });
  return events;
}

// occasional anomalies, one rule at a time, so each flag type gets demonstrated
let cycle = 0;
function anomalyBatch() {
  const events = [];
  const kind = cycle % 5;
  if (kind === 0) {
    // 1. insecure HTTP call
    events.push({ projectKey, type: 'outgoing', api: 'http://legacy-partner-api.example.com/sync', method: 'GET', duration: rand(150, 300), status: 200 });
  } else if (kind === 1) {
    // 2. repeated auth failures on the same endpoint
    for (let i = 0; i < 6; i++) {
      events.push({ projectKey, type: 'incoming', api: '/api/login', method: 'POST', duration: rand(50, 120), status: 401 });
    }
  } else if (kind === 2) {
    // 3. sudden traffic spike on maps API
    for (let i = 0; i < 20; i++) {
      events.push({ projectKey, type: 'outgoing', api: 'https://maps.googleapis.com/geocode', method: 'GET', duration: rand(200, 400), status: 200 });
    }
  } else if (kind === 3) {
    // 4. repeated 500s
    for (let i = 0; i < 4; i++) {
      events.push({ projectKey, type: 'outgoing', api: 'https://api.twilio.com/messages', method: 'POST', duration: rand(100, 300), status: 500 });
    }
  } else if (kind === 4) {
    // 5. abnormally large response
    events.push({ projectKey, type: 'incoming', api: '/api/orders/export', method: 'GET', duration: rand(400, 900), status: 200, responseSize: 6 * 1024 * 1024 });
  }
  cycle++;
  return events;
}

async function tick() {
  const events = healthyBatch();
  if (Math.random() < 0.35) events.push(...anomalyBatch());
  try {
    const res = await postJSON(new URL('/api/ingest/batch', backendUrl).toString(), { events });
    console.log(`sent ${events.length} events → ${res.status}`);
  } catch (e) {
    console.error('failed to send batch:', e.message);
  }
}

console.log(`Simulating outgoing traffic for project ${projectKey} → ${backendUrl}`);
console.log('Press Ctrl+C to stop.\n');
tick();
setInterval(tick, 3000);
